[Feature, WIP] Add zoom rotate
v8hid/infinite-zoom-automatic1111-webui pull request #34
Opened 2023-04-18 20:46 UTC by deklesen

This PR adds the option to rotate the image before inpainting, making for a nice combined zoom & rotate effect.

See an example here: 

https://user-images.githubusercontent.com/19559859/232900543-22a3153d-4a08-4355-82e1-03a933aecedc.mp4

One obvious problem are the black borders in the generated video. Although this can be fixed by cropping the video a bit afterward, that is not an ideal solution.

Thus, this is marked as a WIP for now. I will see what I can do, but I don't think there is a straight-forward solution. With a little bit of rewriting of the create_zoom_single function, it should be doable though: first generate all the outpainted images, then create all the interpolated frames only at the end... 

You can merge it already, or leave it as-is for now until I do more progress. No preference from my side.

2023-04-20 03:14 UTC, v8hid commented
Good job, keep it up. I will merge it when completed it.
I have an idea for you to eliminate the black areas. try to increase the rendering size by a margin let's say (50px * 50 px margin) then you can exclude the margin from your frames and the problem will be fixed.

2023-04-20 23:00 UTC, GeorgLegato commented
let us in the future first PR into develop branch, so we have a chance to test and pre-integrate better
nice hypnorotate

2023-04-20 23:04 UTC, GeorgLegato approved these changes
ok, it is a internal feature for now, since no gui-controls yet.

2023-04-20 23:12 UTC, deklesen commented
Hi, so I have a new version that fixes the black borders! I rewrote the create_zoom_single function to first create the outpainted images and then finally make the interpolated frames...

It looks a bit like magic now.... But it works, at least it looks like it does. I will test it further and then push it on the weekend.

2023-04-20 23:48 UTC, GeorgLegato requested changes
please REBASE from develop, so you get the upscale feature in. it will mess up your rotate changes first, because upscale has to modifiy "currentImage, prevImage etc"
do no merge to main without develop-step

2023-04-20 23:56 UTC, deklesen commented
Yes, i will rebase to develop.. can i then edit this PR to merge into develop instead of main? Never had that case before.. or do i have to create a new one 🥹

But i will probably not have time until sunday to do the rebase & testing of my new magic code 🥴

2023-04-20 23:57 UTC, GeorgLegato commented
> Yes, i will rebase to develop.. can i then edit this PR to merge into develop instead of main? Never had that case before.. or do i have to create a new one 🥹
> 
> But i will probably not have time until sunday to do the rebase & testing of my new magic code 🥴

rebase FROM develop into your PR-branch. then we are in sync. PR target should be develop. should be possible to change target branch

2023-04-22 17:10 UTC, v8hid commented
@deklesen You should pull a request to the develop branch, I close this one.

2023-04-22 17:10 UTC, closed without merging